name: Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Build:checkout"
      uses: actions/checkout@master
    - name: 'Build:dockerimage'
      uses: docker/build-push-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: xyz-network/echo
        tags: latest
