name: Docker Image

on:
  push:
    branches:
      - master
      - '!*no-ci*'
      - '!*skip-ci*'
    tags:
      - 'v*'
      - '!*no-ci*'
      - '!*skip-ci*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: XYZ-Network/echo/echo
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
        dockerfile: Dockerfile
        tag_names: true